### ISSUE TITLE
iOS Remote Debugging

### ISSUE THREAD

**Issue by sterling0x1** [ant4g0nist/vegvisir#1]
`[Thu Jun 22 2017 06:05:14]	platform select remote-ios
[Error]	There was an error while running the command. Error:LLDBController instance has no attribute 'process'`

`[Thu Jun 22 2017 06:09:29]	process connect connect://192.168.1.9:1337
[Error]	There was an error while running the command. Error:LLDBController instance has no attribute 'process'`

Debugserver on device do respond. Any idea how to fix it?

**Comment by ant4g0nist** [comment]
Hey, vegvisir supports osx. Currently, vegvisir gets initialized only with "target create". Need more improvements to work as normal lldb :) thanks for pointing this out.

**Comment by sterling0x1** [comment]
I see. You're more than welcome!
Looking forward for future updates, vegsivir looks pretty neat :) well done indeed!

**Comment by ant4g0nist** [comment]
thanks :)

**Comment by ant4g0nist** [comment]
hey, shall i close this issue? will work on it later.

**Comment by sterling0x1** [comment]
Oh yeah sure, I'll close it buddy :)
