### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by piaoyunsoft** [ant4g0nist/vegvisir#2]
➜  vegvisir git:(master) ✗ python -V
Python 2.7.13
➜  vegvisir git:(master) ✗ python vegvisir.py
Fatal Python error: PyThreadState_Get: no current thread
[1]    5705 abort      python vegvisir.py
➜  vegvisir git:(master) ✗

**Comment by ant4g0nist** [comment]
Hey, I have mentioned in the ReadMe already, lldb works with default python that comes with the os. /usr/bin/python (version->Python 2.7.10). Check the read me :)
